WebApplication1/Models/ClientesModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class ClientesModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Endereco { get; set; }
        public string Telefone { get; set; }
        public string DataNascimento { get; set; }
        public string DataCadastro { get; set; }
        public string Senha { get; set; }
        public decimal SaldoConta { get; set; }
        public decimal SaldoContaBTC { get; set; }
    }
}

WebApplication1/Models/ErrorViewModel.cs
namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication1/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class ClienteController : Controller
    {
        private readonly DataAccess _dataAccess;
        public ClienteController(DataAccess dataAccess)
        {
            _dataAccess = dataAccess;
        }
        public IActionResult Index()
        {
            try
            {
                var cliente = _dataAccess.ListarClientes();
                return View(cliente);
            }
            catch (Exception ex)
            {
                var cliente = _dataAccess.ListarClientes();
                TempData["MensagemErro"] = "Ocorreu um erro na criação do usuároio";
                return View(cliente);
            }
        }
    }
}

WebApplication1/Controllers/InventarioController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers
{
    public class InventarioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebApplication1/Views/Cliente/Index.cshtml
<!--
    ESSES ARQUIVOS SÃO SOBRE O QUE ESTA DENTRO
    DA PÁGINA, E O SHARED É O QUE FICA QUANDO,
    TROCA PARA OUTRA PAGINA, COMO A BARRA, ELA FICA...
-->
@{
    ViewData["Title"] = "Lista de clientes";
}
@model List<WebApplication1.Models.ClientesModel>

<body style="background-color: #D9CEBC">

    <div class="text-center">
        <h1 class="display-4">Lista de clientes</h1>
        <p> Teste de cadastro aqui</p>


        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Endereço</th>
                    <th scope="col">Telefone</th>
                    <th scope="col">Conta (BRL)</th>
                    <th scope="col">Conta (BTC)</th>
                </tr>
            </thead>

            <tbody>
                @if (Model.Count() > 0)
                {
                    @foreach (var cliente in Model)
                    {
                        <tr>
                            cliente.Id = Convert.ToInt32(reader["idCliente"]);
                            cliente.Nome = reader["nome"].ToString();
                            cliente.SaldoConta = Convert.ToDecimal(reader["saldoConta"]);
                            cliente.SaldoContaBTC

                            <td>@cliente.Id</td>
                            <td>@cliente.Nome</td>
                            <td>@cliente.SaldoConta</td>
                            <td>@cliente.SaldoContaBTC</td>
                        </tr>
                        
                    }
                }

                <tr>
                    <th scope="row">1</th>
                    <td>M</td>
                    <td>Otto</td>
                    <td>mdo</td>
                    <td>twitteraaaaaa</td>
                    <td>twitteraxippuden</td>
                </tr>
                <tr>
                    <th scope="row">2</th>
                    <td>Jacob</td>
                    <td>Thornton</td>
                    <td>fat</td>
                    <td>twitteraaaaaa</td>
                    <td>twitteraxippuden</td>
                </tr>
                <tr>
                    <th scope="row">3</th>
                    <td>Larry</td>
                    <td>the Bird</td>
                    <td>twitter</td>
                    <td>twitteraa</td>
                    <td>twitteraxippuden</td>
                </tr>

            </tbody>
        </table>


    </div>


    <!--Cadastrar usuário-->
    <div style="
        position: relative;
        left: 10px;
        height: 450px;
        width: 500px;
        background-color: #877251;
        border-radius: 1%;
 ">

        <div class="aiin" style="
            position: relative;
            left: 120px;
            top: 30px;
             ">
            <h2 style="position: relative; left: 50px;">Cadastro</h2>
            <div>            
                <label for="exampleInputEmail1">Email</label>
                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                        placeholder="Email" style="width: 250px;">
            </div>

            <div>
                <label for="exampleInputPassword1">Nome de usuario</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Repetir senha"
                       style="width: 250px;">
            </div>

            <div>
                <label for="exampleInputPassword1">Repetir senha</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Repetir senha"
                       style="width: 250px;">
            </div>
        
            
            <div>
                <label for="exampleInputPassword1">Senha</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Senha"
                       style="width: 250px;">
            </div>

            <div>
                <label for="exampleInputPassword1">Repetir senha</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Repetir senha"
                       style="width: 250px;">
            </div>
                <a class="btn btn-primary" style="position: relative;width: 300px;top: 60px; 
                background-color: #144114; border: #011e01;"> Cadastrar </a>

        </div>
   </div>

    <!-- Login -->
    <div style="
        position: relative;
        left: 540px;
        top: -450px;
        height: 450px;
        width: 500px;
        background-color: #877251;
        border-radius: 1%;

        "> <!-- div -->

        <div style="
            position: relative;
            left: 120px;
            top: 100px;

            "> <!-- conjunto dos inputs -->
            <h2 style="position: relative; left: 70px; top: -50px;">Login</h2>

            <div class="formGrupoEmail">
                <label for="exampleInputEmail1">Email</label>
                <input type="email" class="inputEmail" id="idInputEmail" aria-describedby="emailHelp"
                       placeholder="Enter email" style="width: 250px;">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password"
                       style="width: 250px;">
            </div>

            <button type="submit" class="btn btn-primary "
                    style="position: relative;width: 300px;right: 30px;top: 115px;background-color: #144114; border: #011e01;">
                Entrar
            </button>
        </div>
    </div>

</body>

WebApplication1/Views/Home/Index.cshtml
<!--
    ESSES ARQUIVOS SÃO SOBRE O QUE ESTA DENTRO
    DA PÁGINA, E O SHARED É O QUE FICA QUANDO,
    TROCA PARA OUTRA PAGINA, COMO A BARRA, ELA FICA...
-->

@{
    ViewData["Title"] = "Página inicial";
}

<body style="background-color: #D9CEBC">
    <div class="text-center">
        <h1 class="display-4">Bem Vindo!!</h1>
        <p> Teste de cadastro aqui</p>


        <div class="Teste" style="background-color:#877251; border-radius:10px; ">
            <p>a</p>
            <p>a</p>
            <p>a</p>
            <p>a</p>
            <p>a</p>
        </div>
    </div>

</body>

WebApplication1/Views/Inventario/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<body style="z-index: 1; background-color: #9AC09B; width: 100%; height: 200vh; ">


    <!--DIV DO CENTRO-->

    <div class="divAnalytic" style=" 
    z-index: 1; 
    position: relative; 
    width: 600px; 
    height: 580px; 
    align-items: center; 
    background-color: #5F9690;
    left: 295px; 
    border-radius: 1%;">aaa</div>
    

    <!--DIV DA ESQUERDA-->
    <div class="usrDiv" style="
    z-index: 1; 
    position: relative; 
    height: 580px; 
    right: 105px;
    top: -580px;
    width: 391px;
    color: #073308; 
    background-color: #5F9660; 
    border-radius: 1%;">

        <div class="informações" style="  position: relative;  height: 280px;  width: 391px;  border-radius: 1%;
        background-color: rgba(255, 255, 255, 0.17); top: 300px;">
            <div>
                <h6>Fundos: </h6>
                <h6>Teste 2</h6>
                <h6>Teste 2</h6>
                <h6>Teste 1</h6>
                <button class="button1" style="background-color: #144114; border: #011e01;">Depositar</button>
                <button class="button1" style="background-color: #144114; border: #011e01;"></button>
                <button class="button1" style="background-color: #144114; border: #011e01;">Testar</button>
            </div>
        </div>
        <div class="usrImage" style="position: relative; height: 130px; width: 130px; background-color: black;
        border-radius: 50%; left: 134px; top: -250px;"></div>

        <h4 class="nomeDeUsr" style="position: relative; left: 154px; top: -220px;">Usuário</h4>
    </div>





    <!-- DIV DA DIREITA -->
    <div style="
    position: relative;
    height: 580px;
    width: 340px;
    left: 890px;
    top: -800px;
    border-radius: 1%;
    background-color: #5F9660;">

        <!-- Div de separação dos colocados-->
        <ul class="list-group" style="position: relative;  width: 320px;  left: 10px;top: 10px;">

            <!-- Linha da lista-->
            <li class="list-group-item" aria-disabled="true" style="height: 70px;">
                <!-- Div de informações -->
                <div style="position: absolute;width: 308px; height: 55px; left: 5px; top: 5px; border-style: solid; border-color:#054e05 ;
                background-color: #0a8d0a6f; align-items: center;">
                    <!--  Colocação-->
                    <div style="position: relative;left: 40px; top: 10px; width: 2px; height: 30px; background-color: black; "></div>
                    <!-- Foto so usuário-->
                    <div style="position: absolute; width: 40px; height: 40px; background-color: #011e01;border-radius: 50%; left: 50px; bottom: 5px;">
                        <img src="..." class="d-block w-100" alt="usrImage">
                    </div>
                </div>

            </li>

            <li class="list-group-item" style="height: 70px;">
                <!-- Div de informações -->
                <div style="position: absolute;width: 308px; height: 55px; left: 5px; top: 5px; border-style: solid; border-color:#054e05 ;
                background-color: #0a8d0a6f; align-items: center;">
                    <!--  Colocação-->
                    <div style="position: relative;left: 40px; top: 10px; width: 2px; height: 30px; background-color: black; "></div>
                    <!-- Foto so usuário-->
                    <div style="position: absolute; width: 40px; height: 40px; background-color: #011e01;border-radius: 50%; left: 50px; bottom: 5px;">
                        <img src="..." class="d-block w-100" alt="usrImage">
                    </div>
                </div>
            </li>

            <li class="list-group-item" style="height: 70px;">
                <!-- Div de informações -->
                <div style="position: absolute;width: 308px; height: 55px; left: 5px; top: 5px; border-style: solid; border-color:#054e05 ;
                background-color: #0a8d0a6f; align-items: center;">
                    <!--  Colocação-->
                    <div style="position: relative;left: 40px; top: 10px; width: 2px; height: 30px; background-color: black; "></div>
                    <!-- Foto so usuário-->
                    <div style="position: absolute; width: 40px; height: 40px; background-color: #011e01;border-radius: 50%; left: 50px; bottom: 5px;">
                        <img src="..." class="d-block w-100" alt="usrImage">
                    </div>
                </div>
            </li>

            <li class="list-group-item" style="height: 70px;">
                <!-- Div de informações -->
                <div style="position: absolute;width: 308px; height: 55px; left: 5px; top: 5px; border-style: solid; border-color:#054e05 ;
                background-color: #0a8d0a6f; align-items: center;">
                    <!--  Colocação-->
                    <div style="position: relative;left: 40px; top: 10px; width: 2px; height: 30px; background-color: black; "></div>
                    <!-- Foto so usuário-->
                    <div style="position: absolute; width: 40px; height: 40px; background-color: #011e01;border-radius: 50%; left: 50px; bottom: 5px;">
                        <img src="..." class="d-block w-100" alt="usrImage">
                    </div>
                </div>
            </li>

            <li class="list-group-item" style="height: 70px;">
                <!-- Div de informações -->
                <div style="position: absolute;width: 308px; height: 55px; left: 5px; top: 5px; border-style: solid; border-color:#054e05 ;
                background-color: #0a8d0a6f; align-items: center;">
                    <!--  Colocação-->
                    <div style="position: relative;left: 40px; top: 10px; width: 2px; height: 30px; background-color: black; "></div>
                    <!-- Foto so usuário-->
                    <div style="position: absolute; width: 40px; height: 40px; background-color: #011e01;border-radius: 50%; left: 50px; bottom: 5px;">
                        <img src="..." class="d-block w-100" alt="usrImage">
                    </div>
                </div>
            </li>

        </ul>

    </div>
    
    
    <!-- DIV INFERIOR -->
    <div style="position: relative; width: 1342px; height: 700px; background-color: #5F9660; top: -510px; left: 3px; border-radius: 1%; ">


        <!-- Slide -->
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" style="position: relative; top: 50px; width: 1100px;height: 500px;
  left: 100px; background-color: #011e01;">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="..." class="d-block w-100" alt="imagem" style="width: 200px;">
                </div>
                <div class="carousel-item">
                    <img src="..." class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="..." class="d-block w-100" alt="...">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>





</body>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Uniforme Express</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Uniforme Express</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!--
                    CONFIGURAÇÕES DA BARRA SUPERIOR:
                -->
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <!--asp-controller: indica qual o controlador-->
                            <!--Aqui é o que vai escrito depois da barra */Home*:-->
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item"><!--/Usuarios:-->
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item"><!--/Inventário:-->
                            <a class="nav-link text-dark" asp-area="" asp-controller="Inventario" asp-action="Index">Inventário</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!--
        CONFIGURAÇÕES DO RODAPÉ:
    -->
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - UniExpress -
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>